id: AF72F06E1
title: Toh_152-The_Questions_of_Sagaramati-v2
type: translation
pechas:
- I60C15467
- IA27FA8AA
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-058-001
  eft-text-version: 1.2.1 2020
  title: Toh_152-The_Questions_of_Sagaramati-v2
alignment_to_base:
  I60C15467/7E7E: B9BF
  IA27FA8AA/0114: B9BF
